### PR TITLE
Fix a issue where the multichannel doesn't deliver initial message co…

### PR DESCRIPTION
**Pull request by supertong**
…rrectly

A possible fix to #273 . This PR will not push through message until the multi channel is ready.

Let me know what you think.

Cheers

### CODE REVIEW

**Comment by slact** [comment]
I'll be reviewing this later tonight.

**Comment by slact** [comment]
Still thinking about it...

**Comment by supertong** [comment]
Forget about this fix. It will cause more problem when the async_call is heavily delayed. Multi-channel fails to deliver any message in that case.

**Comment by slact** [comment]
Ok, thanks for the update.

**Pull request closed without merging**
