### PR TITLE
Make buffer length sync over redis

### PR DESCRIPTION
**Pull request by supertong**
### Background
I am using Nchan to serve messages which have two types - snapshot and delta. The message queue looks like
```
snapshot1 - delta1 - delta1 - delta1 - delta1 - snapshot2 - delta2 ...
```
The requirement is that when a new subscriber connected, Nchan only serve user with the latest snapshot following by deltas. In above example, it will serve user with
```
snapshot2 - delta2...
```
I am able to achieve this functionality through following config
```nginx
server {
    listen 80;
    location = /pub/snapshot {
      nchan_publisher;
      nchan_channel_group test;
      nchan_channel_id test-streaming-data;
      nchan_message_buffer_length 1;
    }

    location = /pub/delta {
      nchan_publisher;
      nchan_channel_group test;
      nchan_channel_id test-streaming-data;
      nchan_message_buffer_length 1000;
    }
  }
```
In this way, I provide two endpoints to publish message into same channel. The differences is that each endpoints will modify the message queue size. 
When I try to scale it with redis, I found out that this only works with memory queue and doesn't work through redis. Therefore, I made few simple tweaks inside the lua script to make it work.

### Changes
* Update channel message queue size and remove dumped messages.
* Remove oldestmsg in `publish.lua`. I guess the purpose of this function is to clean up expired messages? However, if I am right, it only removes the message id from the queue and doesn't actually delete the message object. And, there is already a same function in `get_message.lua`, I reckon this should be enough?

### Questions
* I use `DEL` command to remove dumped messages, but I don't know if it's better to just let it expire by itself? Which means, I remove the message id from queue, but leave the message object to expire.
* Is it really ok to remove the oldestmsg from `publish.lua`?

### CODE REVIEW

**Comment by slact** [comment]
I've been meaning to add this functionality for some time, but I believe it's a little more complicated than the `publish.lua` script. This is because the memory storage engine, which also serves as a cache layer for redis data, does not yet recognize buffer length changes from. Your change would sort of work when dealing with only 1 nginx instance, but would fail when scaling out to several servers. 

> Remove oldestmsg in publish.lua. [...] And, there is already a same function in get_message.lua, I reckon this should be enough?

It's needed in publish.lua to accurately determine current message buffer length in a channel. Messages can expire, and oldestmsg() traverses the message list and removes any keys which have already expired. Without this, if a user has set an expiration time and a maximum buffer length, and then some messages expire, buffer length limits would not be enforced by the script correctly because it would assume the expired messages still exist (because their keys in the list cannot by themselves expire). That's why this function is needed in get_message.lua and publish.lua

> I use DEL command to remove dumped messages, but I don't know if it's better to just let it expire by itself? Which means, I remove the message id from queue, but leave the message object to expire.

You should both delete from the queue, and delete the message.

> Is it really ok to remove the oldestmsg from publish.lua?

No, see above


As soon as I'm finished with redis cluster work (few days), I'll take a close look at this feature. I can't merge this PR yet as it breaks a few things and it'll also take messing with some C to get things working properly. Thanks for the PR and the writeup; I will revisit this in a couple of days.

**Comment by supertong** [comment]
Hey @slact , thanks for replying.
Can't wait for few days 😆 . I dive into the C code myself and agree with you that it's complicated 😰 .
Right now I am thinking of a possible way to implement it.
In `publish.lua`, I am going to add in an extra field called `max_message` in `msg`. It looks like
```
if #msg.data < 5*1024 then
  unpacked= {
    "msg",
    msg.ttl or 0,
    msg.time,
    tonumber(msg.tag) or 0,
    msg.prev_time or 0,
    msg.prev_tag or 0,
    msg.data or "",
    msg.content_type or "",
    msg.eventsource_event or "",
    channel.max_stored_messages
  }
else
  unpacked= {
    "msgkey",
    msg.time,
    tonumber(msg.tag) or 0,
    key.message,
    channel.max_stored_messages
  }
end
```
And then, I should be able to retrieve the `max_stored_messages` in `redis_subscriber_callback`. Then I can pass this message all the way to `nchan_store_channel_head_t` -> `channel_spooler_t` -> `subscriber_pool_t` -> `subscriber_t (internal subscriber)`. After all this I should be able to update the message length on `chanhead` in memstore through `internal_subscriber->respond_message(self, msg)`? What do you think? I haven't got time to implement it, but would like to get some guidance from you if possible. Thanks a lot.

**Comment by slact** [comment]
Wow, you're really digging in there, and your approach is correct, it's what I had in mind when I realized this feature was missing for redis storage. I'm not entirely happy with adding an extra `max_stored_messages` parameter to the message struct -- it adds to an already somewhat bloated (and heavily used) struct, and it's not a piece of data really relevant to the message (unlike msg expiration time). However, it's the most straightforward way to do it. If you implement it like this, I'll either accept it or figure a way to move that parameter out of the message.

In terms of redis stuff, you'll also need to add this data to the get_message.lua script, and I would prefer putting `channel.max_stored_messages` right after the ttl : 
```lua
--publish.lua
unpacked= {
    "msg",
    msg.ttl or 0,
    channel.max_stored_messages,
    msg.time,
    tonumber(msg.tag) or 0,
    msg.prev_time or 0,
    msg.prev_tag or 0,
    msg.data or "",
    msg.content_type or "",
    msg.eventsource_event or "",
  }

--get_message.lua

return {200, ttl, channel.max_stored_messages, tonumber(ntime) or "", tonumber(ntag) or "", tonumber(prev_time) or "", tonumber(prev_tag) or "", ndata or "", ncontenttype or "", neventsource_event or "", subs_count}
```
If you want, I can add a test for this to tests.rb -- not sure if you're using that. I can also walk you through how to run the test harness, if you'd like.

**Comment by supertong** [comment]
Hey @slact ,
  Managed to do it but in a slightly different way from what I described. I added in a short cut in `rdstore.c`
```
ngx_int_t redis_store_channel_max_message(ngx_str_t *channel_id) {
  nchan_store_channel_head_t *head = nchan_store_get_chanhead(channel_id);
  if (head != NULL) {
    return head->max_messages;
  }
  // Return the default value which is unlimited
  return (ngx_int_t) -1;
}
```
It helps `memstore_redis.c` to update memstore chanhead inside `sub_respond_message`.
```
static ngx_int_t sub_respond_message(ngx_int_t status, void *ptr, sub_data_t* d) {
  nchan_msg_t       *msg = (nchan_msg_t *) ptr;
  nchan_loc_conf_t   cf;
  nchan_msg_id_t    *lastid;
  DBG("%p memstore-redis subscriber respond with message", d->sub);

  // Sync max_message from redis store
  cf.max_messages = d->chanhead->max_messages = redis_store_channel_max_message(&d->chanhead->id);
  cf.use_redis = 0;
  cf.buffer_timeout = msg->expires - ngx_time();

  lastid = &d->chanhead->latest_msgid;
```
Regarding the msg returned from `publish.lua`, I added in two more new message types `sz+msg` and `sz+msgkey`. I think it should reduce the usage a little bit? I mean it only sends back buf size if it changed.

I will look into the `test.rb` to finish writing the test cases tonight or tomorrow. It would be great if you can show me how to run the test harness and where to find them as well. 

Let me know what you think.
Also, my editor automatically trim out leading spaces and tailling spaces...which caused conflicts I believe. Do you prefer to keep those spaces? I can add them back to resolve the conflicts if you prefer.

Cheers

**Comment by slact** [comment]
Nice work! But can you please undo those whitespace changes? It's very inconvenient to have whitespace changes when trying to evaluate this PR. Leading whitespace is part of the (somewhat idiosyncratic) style I'm using in Nchan, so please tell your editor to play nice. 

I'm not sure if i'm satisfied with calling `redis_store_channel_max_message(&d->chanhead->id);` on every redis->memory message transfer. Maybe it's just premature optimization talking... I'll do a profiling run a little later.

So please undo the whitespace changes and I'll get you some more detailed feedback.

**Comment by supertong** [comment]
Haha, that's Nchan style! I have undo those whitespace changes and rebase it from the latest master to resolve conflicts.
Regarding the `redis_store_channel_max_message` calls, I assume you are worrying about the calls to `nchan_store_get_chanhead`. I understand your worries and it's already been called in `nchan_store_publish_generic` from `redis_subscriber_callback`. However, it makes sense to me that we syncing the information inside `memstore_redis.c`, because I feel it like a middleware. Hmmm, I will see if I can find a better approach to pass the information.

**Comment by slact** [comment]
Ok, looks good. I'm going to tweak this a little more tonight.

**Comment by slact** [comment]
I've merged this PR into the [redis_propagate_max_messages](/slact/nchan/redis_propagate_max_messages) branch, and cleaned up some copy-pasted code in f2c8b1d64855b2f. I'll do some more testing and see if I can get around calling `redis_store_channel_max_message(&d->chanhead->id)` -- I have an idea about that...

**Comment by slact** [comment]
Alright then, I've reworked it to my satisfaction: 32234bb53dfc06. There is now no extra overhead from calling `redis_store_channel_max_message`, i've removed that entirely. Instead, I've finished exposing subscriber notification functionality ( 91b2101750c7b ) and used that to notify the memstore-redis subscriber when the max_messages value changes. I had thought subscriber notifications would end up being useful, looks like I wasn't wrong. Plus, as a bonus, I also factored out some copypasta. 

I've tested it so far and it works well. Give it a try and let me know it it works for you.

**Comment by slact** [comment]
Fixed publish script in a152427e3a7d0 , and merged changed into [redis_multiserver](/slact/nchan/tree/redis_multiserver) and [redis_cluster](/slact/nchan/tree/redis_cluster) . Will merge into master after another day of tests.

**Comment by supertong** [comment]
Awsome! Thanks @slact , it works great so far. I am very interested in how you implement it. I will dive into the code later.
Good catch on the redis `DEL`, it's a shame that we can't group them together in a single command.
I will let you know if I run into any problems. Thanks again for you help.
l0HFiOtai3t3xIoLK

**Pull request merged**
