### PR TITLE
Fix typos preventing nginx compile with nchan

### PR DESCRIPTION
**Pull request by bkmit**

### CODE REVIEW

**Comment by slact** [comment]
I'm curious, what OS/compiler are you using? I haven't had any build problems with the config as it was, with any of my tests (arch linux, ubuntu, debian, OpenBSD, Fedora, os X 10)

**Comment by bkmit** [comment]
This was nginx 1.8.1 static build by gcc 4.8.4 on ubuntu 14.04 amd64.

**Comment by slact** [comment]
Strange, I had no problems with that combination. Regardless, you are correct about this patch, there should be backslashes before those newlines. Thanks for the patch!

**Comment by bkmit** [comment]
Thanks for merging.
Look like absence of backslashes are relevant only in case if more then one external module us compiled in.

**Comment by slact** [comment]
It's still strange, because I have been able to build the nginx-extras package for ubuntu and debian (which has a while bunch of 3rd party modules + nchan) without issues. This is just an idle curiosity for me though, your fix is correct and I appreciate it. Thanks!

**Pull request merged**
