### PR TITLE
add empty point judgement before using the point

### PR DESCRIPTION
**Pull request by woodyhymns**

### CODE REVIEW

**Comment by slact** [comment]
Eh, this code is for developer debugging only. I don't think it needs memory-allocation-failed checks, it's only going to be used during development.

**Comment by woodyhymns** [comment]
ok

**Comment by slact** [comment]
Thank you for your submission though. I'm curious, are you reading through the code, or do you have a tool to find these?

**Comment by woodyhymns** [comment]
ah ha, yeah, I'm reading through the code, just forgot that they were debugging code:)

**Pull request closed without merging**
